name: Semantic PR Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic:
    name: Check Semantic PR Title and Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          validateSingleCommit: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
